const mongoose = require("mongoose");
const Schema = mongoose.Schema;

const ShopSchema = new Schema({
	act_tag: Number,
	activities: Array,
	address: String,
	authentic_id: {
        type: Number,
        required: true
    },
	business_info: String,
	delivery_fee_discount: Number,
	delivery_mode: Object,
	description: String,
	distance: Number,
	favored: Boolean,
	flavors: Array,
	float_delivery_fee: Number,
	float_minimum_order_amount: Number,
	has_story: Boolean,
	id: String,
	image_path: String,
	is_new: Boolean,
	is_premium: Boolean,
	is_star: Boolean,
	is_stock_empty:Number,
	is_valid:Number,
	latitude:Number,
	longitude:Number,
	max_applied_quantity_per_order: Number,
	order_lead_time: Number,
	platform: Number,
	rating: Number,
	rating_count: Number,
	recent_order_num: Number,
	phone: String,
	next_business_time: String,
	name: String,
	promotion_info: String,
	regular_customer_count: String,
	scheme: String,
	target_tag_path: String,
	type: Number,
	only_use_poi: Boolean,
	out_of_range: Boolean,
	opening_hours: Array,
	posters: Array,
	recommend_reasons: Array,
	tags: Array,
	support_tags: Array,
	supports: Array,
	piecewise_agent_fee: Object,
	recommend: Object,
	theme: Object,
	status: Number
})

module.exports = Shop = mongoose.model("shops", ShopSchema);